### PR TITLE
Why is this here?

### PR DESCRIPTION
**Pull request by GotNoFriends**
Also, I'm banned for abuse. I went in /v and spawned a zombie lol. I would like a unban. Robin banned me without a confirmation from @ImALuckyGuy

### CODE REVIEW

**Comment by TheRevalation** [comment]
@GotNoFriends Robin thought you were a little immature, I never confirmed of it nor did Lucky, but I agree, you need to stay mature, if you want to continue to be here

**Comment by GotNoFriends** [comment]
@TheRevalation Unban me please.

**Comment by xDestroyer217** [comment]
No, also lucky agreed to ban you. @GotNoFriends

**Comment by GotNoFriends** [comment]
@xDestroyer217 Then remove this plugin.

**Comment by TheRevalation** [comment]
@GotNoFriends You have already waived the license, We can now keep it and edit it all we want.

**Comment by GotNoFriends** [comment]
@TheRevalation I will remove the waived licence for you. Remove the repo.

**Comment by GotNoFriends** [comment]
@TheRevalation I have removed it. Now remove the plugin.

**Comment by TheRevalation** [comment]
@GotNoFriends Um, I coded this plugin from the start, I can waive this license anytime I want for anybody also General, so rewaived for @xDestroyer217 and @ImALuckyGuy

**Comment by GotNoFriends** [comment]
@TheRevalation You have also been removed.

**Comment by TheRevalation** [comment]
@GotNoFriends You cant remove me or I can DMCA your plugin

**Comment by GotNoFriends** [comment]
@TheRevalation Idc. Your removed. Go ahead and DCMA it idgaf.

**Comment by xDestroyer217** [comment]
Are you seriously pushing over because Lucky banned you? Lovely!

**Comment by TheRevalation** [comment]
@GotNoFriends Point is, I dont want to DMCA your plugin, but this plugin cannot be DMCA'd and it will stay here.

**Comment by GotNoFriends** [comment]
@TheRevalation I will take legal action if you do not remove this.

**Comment by xDestroyer217** [comment]
DMCA is a legal action.

**Comment by GotNoFriends** [comment]
@xDestroyer217 Thats what I ment.

**Comment by xDestroyer217** [comment]
@GotNoFriends You said you dont give a crap if we DMCA you, but you care if you DMCA us? Just k..

**Comment by TheRevalation** [comment]
@GotNoFriends If you try to DMCA us, I can DMCA you too, and this plugin will stay because I waived the license, because I coded the original plugin and the license.

This is waived for these people and you cannot DMCA us.

**Comment by GotNoFriends** [comment]
@TheRevalation I've removed my original repo, do what ever you want with this plugin. Just leave my credit in plugin.yml and in the Utils and shit.

**Comment by GotNoFriends** [comment]
@xDestroyer217 That alright?

**Comment by xDestroyer217** [comment]
@GotNoFriends We are making a new plugin for Tatsu, though. fine with me.

**Comment by GotNoFriends** [comment]
@xDestroyer217 Alright.

**Comment by GotNoFriends** [comment]
@xDestroyer217 Could I get unbanned, please.

**Comment by TheRevalation** [comment]
@GotNoFriends Up to lucky

**Comment by ImALuckyGuy** [comment]
If you promise to behave, I'll unban you.

**Pull request merged**
